spring:
  application:
    name: ai-cloud
  
  # Spring AI Ollama 配置
  ai:
    ollama:
      base-url: http://34.125.206.97:11434
      chat:
        options:
          model: qwen2.5vl:3b
          temperature: 0.7


# Whisper 语音识别配置
whisper:
  server:
    url: http://34.125.206.97:8083
    inference-path: /inference
    timeout: 60000  # 超时时间（毫秒）

